(function(g){
"use strict";
function utf8Len(s){return new TextEncoder().encode(s).length}
function escapeNonASCII(s){return Array.from(s).map(ch=>{const cp=ch.codePointAt(0);if(cp<128)return ch;if(cp<=0xffff)return "\\u"+cp.toString(16).padStart(4,"0");const n=cp-0x10000,hi=0xd800+(n>>10),lo=0xdc00+(n&1023);return "\\u"+hi.toString(16).padStart(4,"0")+"\\u"+lo.toString(16).padStart(4,"0")}).join("")}
function mapFrom(v){if(v instanceof Map)return v;const m=new Map;if(typeof v==="string")for(const line of v.split(/\r?\n/)){const p=line.indexOf("=");if(p>0){const a=line.slice(0,p).trim(),b=line.slice(p+1).trim();if(a&&b)m.set(a,b)}}else if(v&&typeof v==="object")for(const [a,b] of Object.entries(v))if(a&&b)m.set(a,b);return m}
function lex(src){let out="",i=0,quote=null,esc=false,space=false;while(i<src.length){const c=src[i],n=src[i+1];if(quote){out+=c;if(esc)esc=false;else if(c==="\\")esc=true;else if(c===quote)quote=null;i++;continue}if(c==="'"||c==='"'){if(space&&/[\w$]/.test(out.at(-1)||""))out+=" ";space=false;quote=c;out+=c;i++;continue}if(c==="/"&&n==="/"){i+=2;while(i<src.length&&src[i]!=="\n")i++;space=true;continue}if(c==="/"&&n==="*"){i+=2;while(i<src.length-1&&!(src[i]==="*"&&src[i+1]==="/"))i++;i+=2;space=true;continue}if(/\s/.test(c)){space=true;i++;continue}const prev=out.at(-1)||"";if(space&&/[\w$]/.test(prev)&&/[\w$]/.test(c))out+=" ";space=false;out+=c;i++}return out.trim()}
function rename(src,map){map=mapFrom(map);let out="",i=0,quote=null,esc=false;while(i<src.length){const c=src[i];if(quote){out+=c;if(esc)esc=false;else if(c==="\\")esc=true;else if(c===quote)quote=null;i++;continue}if(c==="'"||c==='"'){quote=c;out+=c;i++;continue}if(/[A-Za-z_$]/.test(c)){let j=i+1;while(j<src.length&&/[A-Za-z0-9_$]/.test(src[j]))j++;const t=src.slice(i,j);out+=map.get(t)??t;i=j;continue}out+=c;i++}return out}
function decimals(src){let out="",i=0,quote=null,esc=false;while(i<src.length){const c=src[i];if(quote){out+=c;if(esc)esc=false;else if(c==="\\")esc=true;else if(c===quote)quote=null;i++;continue}if(c==="'"||c==='"'){quote=c;out+=c;i++;continue}if(c==="0"&&src[i+1]==="."&&/\d/.test(src[i+2]||"")&&!/[\w$]/.test(src[i-1]||"")){out+=".";i+=2;continue}out+=c;i++}return out}
function canonicalize(src,map){return decimals(rename(lex(escapeNonASCII(src)),map))}
function checkProfile(profile){if(!profile||!Array.isArray(profile.tokens)||typeof profile.alphabet!=="string")throw new Error("Bad M64 profile");if(profile.tokens.length>64)throw new Error("M64 profile exceeds 64 tokens");const A=Array.from(profile.alphabet);if(A.length!==64||new Set(A).size!==64)throw new Error("M64 alphabet must contain 64 unique characters");return profile}
function tokenize(src,tokens){if(tokens.length>64)throw new Error("M64 profile exceeds 64 tokens");for(const ch of src)if(ch.charCodeAt(0)>127)throw new Error("Canonical source is not ASCII");const scan=tokens.map((text,index)=>({text,index})).sort((a,b)=>b.text.length-a.text.length),out=[];for(let i=0;i<src.length;){let hit=null;for(const t of scan)if(src.startsWith(t.text,i)){hit=t;break}if(hit){out.push(0x80+hit.index);i+=hit.text.length}else{out.push(src.charCodeAt(i));i++}}return Uint8Array.from(out)}
function encode64(bytes,alphabet){const A=Array.from(alphabet);if(A.length!==64||new Set(A).size!==64)throw new Error("Bad M64 alphabet");let out="";for(let i=0;i<bytes.length;i+=3){const b0=bytes[i],b1=i+1<bytes.length?bytes[i+1]:0,b2=i+2<bytes.length?bytes[i+2]:0,n=(b0<<16)|(b1<<8)|b2;out+=A[(n>>18)&63]+A[(n>>12)&63];if(i+1<bytes.length)out+=A[(n>>6)&63];if(i+2<bytes.length)out+=A[n&63]}return out}
function decode64(text,alphabet){const A=Array.from(alphabet),M=new Map(A.map((c,i)=>[c,i])),v=[];if(A.length!==64||new Set(A).size!==64)throw new Error("Bad M64 alphabet");for(const c of Array.from(text).filter(c=>!/\s/.test(c))){if(!M.has(c))throw new Error("Character outside M64 alphabet");v.push(M.get(c))}if(v.length%4===1)throw new Error("Invalid M64 length");const out=[];for(let i=0;i<v.length;i+=4){const a=v[i],b=v[i+1],c=v[i+2],d=v[i+3];if(a===undefined||b===undefined)throw new Error("Invalid M64 tail");const n=(a<<18)|(b<<12)|((c??0)<<6)|(d??0);out.push((n>>16)&255);if(c!==undefined)out.push((n>>8)&255);if(d!==undefined)out.push(n&255)}return Uint8Array.from(out)}
function hydrate(payload,profile){checkProfile(profile);const bytes=decode64(payload,profile.alphabet);let out="";for(const b of bytes){if(b<128)out+=String.fromCharCode(b);else if(b<0xc0){const i=b-0x80;if(profile.tokens[i]===undefined)throw new Error("Undefined token index "+i);out+=profile.tokens[i]}else throw new Error("Reserved token byte 0x"+b.toString(16))}return out}
function stage(src,map,profile){checkProfile(profile);const canonical=canonicalize(src,map),abstract=tokenize(canonical,profile.tokens),payload=encode64(abstract,profile.alphabet);return{canonical,abstract,payload,hydrated:hydrate(payload,profile)}}
function mappedEntry(entry,map){if(!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(entry||""))throw new Error("Entry must be a JavaScript identifier");return mapFrom(map).get(entry)??entry}
function validateArtifact(a){if(!a||a.kind!=="chisel-m64-artifact"||a.version!==1)throw new Error("Unsupported artifact package");if(a.type!=="javascript")throw new Error("Unsupported artifact type");if(a.runtime!=="CHISEL-PURE1")throw new Error("Unsupported runtime");if(!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(a.entry||""))throw new Error("Bad artifact entry");checkProfile(a.profile);if(typeof a.payload!=="string")throw new Error("Artifact payload missing");return a}
g.ChiselM64={utf8Len,mapFrom,canonicalize,checkProfile,tokenize,encode64,decode64,hydrate,stage,mappedEntry,validateArtifact};
})(globalThis);
